mairror_api:
    secrets:
        values:
            S3_BUCKET_RAW_NAME: ENC[AES256_GCM,data:ZcWfD9iZ2jwhZWEWaag=,iv:hrMRYpJ531uzerUKXGzPjviuip2BSQxd7sGpN7bOgag=,tag:oE7TLbIPVnTAB2l5ms4lag==,type:str]
            API_KEY: ENC[AES256_GCM,data:yKgH4tHTeoVLZtJxtCIzJZq4V4ZL/W//1jZ883zVVq4TU+/beHTJPQ==,iv:QJ5nfiqHnRHpRl2UUKT3uynzF2q+0lmRFCB4wO4aQ6s=,tag:vOHBbDB+g+BoBVEP8xOdtA==,type:str]
            DATABASE_NAME: ENC[AES256_GCM,data:jOwLpoJw7w==,iv:0ZYPpVU132n4/1WYxX7BFG/1YzmM0iXnbCdtd+NxMu8=,tag:3u41Jsz4LxcZga9S0zkFJw==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:H9fF0wS930fP9NhElENPWCU2+U0Mao7YfxxTXJ/97pIGskv5khK5kGRg1VUk4EDj1pVMl1I93LOCoJ362saii69moZisKREDDz3frwYTWREEQRt1sjaH1wrj3hjnhiWuvTysep4zOtZu2ZU=,iv:jUFGBKUzzBzT/wGteqGJegjg5gDTwdt8PK/TRqAxrnc=,tag:EW/q37MpVowblmausRjk/g==,type:str]
            DEBUG: ENC[AES256_GCM,data:00YZG0g=,iv:rZ4XOPKPMeLc4L5RGINOeWEgpyvyzNKQUHhBOwT2lP0=,tag:dd+Ix6Qz8yd/cxz8T0oLcA==,type:str]
            ENVIRONMENT: ENC[AES256_GCM,data:C6WmPVWwrLSAZA==,iv:1ZM+DNjwjR0MgGOXfC37uRMi2csrqt/Y7dwEwXYTmm4=,tag:FpmAGBP12QDHAMLGVEHmlw==,type:str]
            LOG_LEVEL: ENC[AES256_GCM,data:JjDvXg==,iv:QnhW0VpaKeLw8JPOsgvGo4VmlT0TggYBso02912YkjA=,tag:1OHHn5W843T+wkRFW+Tp9Q==,type:str]
            SENTRY_DSN: ENC[AES256_GCM,data:lHGcCv2Wf9MwMxeq+NH9lTnQWknkbYlGN5FRLo0JK/0ew1xJUAz8jXEnv0ENUGfLbnet2lxRAKJIKWS3fQ1JWN1K7+/moRRlU4E=,iv:3WYh/+5K0QnpXJ4e6hrHlPZ0h0g7Ywm9pfTr40fmNZU=,tag:d6/eNLi3ecsQxAFsJ7H7xQ==,type:str]
            WEB_CONCURRENCY: ENC[AES256_GCM,data:5A==,iv:edZj/h2jT7v30azG61Wx2QpAhYvP2X2cEDfUckH/B4U=,tag:pyeSkrrlNRxAf2g96uVd7w==,type:str]
mairror_bot:
    secrets:
        values:
            API_KEY: ENC[AES256_GCM,data:TZgZJIONU1nS5GwqHnMYBG7LZ1RCKGua80IFj8TEBi4ZFcWPGrmdrg==,iv:J0/nhUp8mW5aCTkMIQSXhOfrjOnl0rAwKwyZJ5A2sEw=,tag:pMUSVUNdXet3gLSpRMRoKQ==,type:str]
            BOT_TELEGRAM_TOKEN: ENC[AES256_GCM,data:d1HULD1uYOUnZBYcKheGsOzVp6jbRIanfmiSDB1FEeSEfP+tnX6gzIbi/7Ea8w==,iv:DE56UdN7K9GmZSm8N3odK5cHI8kzy7ee90n2LDvO8/Y=,tag:x30fyelBkujmoeq6owOHeg==,type:str]
            API_URL: ENC[AES256_GCM,data:SDF7JhsC+cahSGbopG+rCE1/Y23Q9p8=,iv:xotsUG+c+jhLfRE3C1948zbNfBjCLDHGmHHcISO7zwo=,tag:26mpawkKRB/bSO5Wy6RAJQ==,type:str]
            SLACK_WEBHOOK_URI: ENC[AES256_GCM,data:tfKbQR2F5MSfBvjA/7hZAvXyMP3yOGT8wtfYuvBxu3DxKmmeSH0h/4MqcZxzhUPnt5SPfwywMNaRcgiGqpEHjUUmztoGWHPQbwvG+q6dBA==,iv:Zcd7yP22IAfjSvVa6xefjsvYjVZnVcC60m7KrtlFOcM=,tag:fcOr+dC0EhsSfahB1UZEnw==,type:str]
mairror_processor:
    secrets:
        values:
            NUM_MESSAGES: ENC[AES256_GCM,data:WWk=,iv:wWic5HaF1i7APko7Id+m2N6iDNhXFjRVBaqySJwdcu4=,tag:X4MkkIA07fnT9MMtaClePA==,type:str]
            API_URL: ENC[AES256_GCM,data:BVbdhZMvGVQoVH4MzdJdBWP5LNubteE=,iv:XoPkqzrt/3dDNKSWxAonKBKsILv++m8tUuw/5UeAYMM=,tag:yZORr4eLCm7d8gbi2irf0Q==,type:str]
            API_KEY: ENC[AES256_GCM,data:0xf7XZQpjdLsr7XYwGa2zR2LZ7dINtXiL9al7zzkai1RpNtKDrBSsg==,iv:dTVTz+D59E+tSbkosHqA6zQo7nh91OBs2pv9T5Gxxgc=,tag:dYbb4fjItdm4um+kXbAKZg==,type:str]
            WAIT_TIME_SECONDS: ENC[AES256_GCM,data:bz0=,iv:yroRnNY6sbxzTYRl2g5wlYt1un0hFhs9L6kbN/uthgs=,tag:zkfViuFctvI7DxfcpqKyHw==,type:str]
            AWS_REGION: ENC[AES256_GCM,data:A+4k8B7ldEE/y/eW,iv:nVaOKFpuA1UhUZmRYFA7XrGCdmS5kh4ZjIWEoVm9YVI=,tag:EJpHnCOABFBwa/OPhskNsg==,type:str]
            AWS_DEFAULT_REGION: ENC[AES256_GCM,data:cCltpM3ghUC7f3Sn,iv:DK+1d5eF+x8EHAoJc5zFkT+J/hpUggAzFmSvf2GPBDY=,tag:nfPnIfSbMhd4Q8ESgVbSsA==,type:str]
            DATABASE_NAME: ENC[AES256_GCM,data:nz9VB+7Rjw==,iv:Rzf2hAoJLrqXrU0DCx7GztUrftdmSNlxNLYPOIF+B2k=,tag:G7gN/Bm1wJTKnNcCEWbFhw==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:EujK9BAE3GBiLFcpKWx3m7A9x9pM4CIAYIaITOKsqDy28B0nDF8lR5RROulAua1TsRqLaeLxEkyBjxU1kv6DajKx8lQZ32yDIPsHEJob4jPMhhiyhgIoa13vK7/rgcZgHq6s1JAlBb9XdyQ=,iv:sETXPK/QZKPLTTmolylY1QI7cIr6oyXV5/QrW3cPy88=,tag:Ftqs9N3zxJ7MAqp9COHXCA==,type:str]
            SQS_CROPPED_QUEUE_NAME: ENC[AES256_GCM,data:jKvNAWKirx488C8=,iv:VWfaGSmc3gkM7+le11fXZFRoZpmqmjQJWOcd+ZXX0SE=,tag:gErfXb2kRfUVx7FIUpGfqw==,type:str]
            SQS_PREDICT_QUEUE_NAME: ENC[AES256_GCM,data:ZKtNGz/51zPswHcXxphH,iv:c3qdKJShSIdHKcNYGEwzBmfXzKjHwWifDDIWNIIkAfs=,tag:RLeI8Cgcuv7Zzk3Vly6tBQ==,type:str]
mairror_predictor:
    secrets:
        values:
            NUM_MESSAGES: ENC[AES256_GCM,data:e10=,iv:Ae02XksDWTMxvZ2OndBtYLgy+m5QaoL6HPEmPdTRwv8=,tag:XaS5Wd7HMehzrqyZRctl0w==,type:str]
            WAIT_TIME_SECONDS: ENC[AES256_GCM,data:LoM=,iv:2SueiKK6y5y3HwAHwiOUV0TEmym6nnUmvi8Q1T8odaY=,tag:+Gv7Xusuz2mmfcJr9++9IA==,type:str]
            AWS_DEFAULT_REGION: ENC[AES256_GCM,data:RBd5ZAU9thmDWOZh,iv:05HB3oytQCiYVWmN1/ieeEJTwfynQIDNkSqsm8hRik4=,tag:hvs4749eNfmSZ7c5jmG9HQ==,type:str]
            MONGO_URI: ENC[AES256_GCM,data:cCCwghElvfChFfbXUUW4MfpvnRAlMraEyi1Wz9UlwIfY9D80eBQDbhmOvmJV75AwFkgiT2nH0KvkJ9VmTf5Jk6jmFMtmUOiCU1T4ysG06DKMOuvutHk6AUQNBNbF8weZJcRpI/KOvR6X7q0W7PREai6pdCzbmG+rCQHUYw==,iv:5UwIR8THjNf5UGkDlab2gwvkV0J8Xw85+2O82RKwoMM=,tag:cHFDjddqq0AWo+XhXNanQw==,type:str]
            MONGO_DATABASE: ENC[AES256_GCM,data:fevct2G79w==,iv:cKCNXC1RDz7tWJyaWAheWrXw9RX1qNMBku3bLf5K1Kk=,tag:NxPkYG4XmV4Zj1jun4n+dg==,type:str]
            MONGO_COLLECTION_FACES: ENC[AES256_GCM,data:7tasY0c=,iv:JF8nEkMeB7xk3ll8ymwQxYlRO/8Ji41mkLONCDCfKIc=,tag:EoxWDxKIby+/B9r6ODi8zA==,type:str]
            MONGO_COLLECTION_PREDICT: ENC[AES256_GCM,data:4YGgF57dWQ==,iv:uv6RyY+D0l3h+G5BHlgWDG/qww1BlCsq1MiPDcQCMiM=,tag:cfs0z8hVpLC0TbEanUp6FA==,type:str]
mairror_front:
    secrets:
        values:
            API_URL: ENC[AES256_GCM,data:hBdGj4PcyXIUyaJk1uJyJqOLtXMWIC4=,iv:YEhEFq6Prj6EjnUjJhdYC9CWkDClGVVZ8iaonGIE9cI=,tag:Z325P/InFP/w75H3TWlD2A==,type:str]
            API_KEY: ENC[AES256_GCM,data:lMjT8OA95NmtTDaLlIRLk6fmkmYSBiKmKI8yIsiJfY2URD9+T3Cnyw==,iv:tdIXmMc6DXEu26Rr/BCs7QXp6ezwRnahs3jw4XoumYs=,tag:1V4CLUm5VA6q/vj3JZzk5A==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:733077684693:alias/mairror-sops
          created_at: "2022-03-11T14:43:13Z"
          enc: AQICAHiUvh+4mSvrQgBQn74eTV2Mg3GioiEjAAveclQGTuHiVgHYu7LuE2erEcYUqNvf0hQ4AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMZYoQClLZCG/L35P5AgEQgDudOQ3r3HWa4Q1uSZTQj/C8tSmaKn2Y6w3mpWqslTP/+4wwQQGLfJCAjoFwUJ6jdChJDI4Osqh06xTjUQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-11T14:43:14Z"
    mac: ENC[AES256_GCM,data:wyZQk/hB5xJJEofYHZ1FCLGywV7IsP5aw5GEFRwn8/nSqxGETVDIRhsjXVuk3dNPRAJNy1l0hFaOoNFvYnyNgbei4ky2KD3HtkjEws5vLNQ7eKXza2b8qTIRVfpLPjMDQWyN2QfqorxG6v94ch50M+G/LIbiINVbdK0Sk5KkZps=,iv:/dLzI4iFzF9TUH+TfA3QDsnLQg7UAEHdNUzsvOl7q+M=,tag:sL8dN7MGCixWotjRnYGesw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
