email: ENC[AES256_GCM,data:xN6eurnkDSiFIgH3S5ViXxi3wy+3ug==,iv:vZ2TS62aeovPFwVrIwao/fyEzPdRbPWx/+zTKHUhWVI=,tag:LSlnzW53eV5doDAQx4muCA==,type:str]
aws:
    hostedzoneID: ENC[AES256_GCM,data:0g2arTN3gnE4b1c7Q4iNeVjGXE5x,iv:u1ZurQUQV1BHlVTVGLz3r9IeDeBs8jiyhOOu2rHid98=,tag:/SKPDSJeyQKNcHyBqtVyaw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:733077684693:alias/mairror-sops
          created_at: "2022-03-11T11:13:31Z"
          enc: AQICAHiUvh+4mSvrQgBQn74eTV2Mg3GioiEjAAveclQGTuHiVgEKxDObcjVBgpwJehb+sV34AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMH24O8bfQ28dD4xggAgEQgDvLRzIO9pa4prH4oM0hIvunEz2Im82staoNh5ikJjyyLPJf7A+lVqL1KpgCupRW2fmXAB+Hev1eKrgK5g==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-11T11:13:31Z"
    mac: ENC[AES256_GCM,data:0JKdoMzDlkqTXtHtBvDnTQbnwj2YTu5+Spt9fb/agio6bJS41/SWhXsCPoPVhv36ZXtFfrOdZjnJIOcazOEGI4dQ5smwlVXEE0zbbXbeWKwVXol5jta1vgNmeb5utYuLTijB3QS3HJjMGVa7EimNcfBwB+nqGVX9Qy0lkD4gBBU=,iv:IShV+cz/2Qc0G5iYkD1g6I8cgW8sTKU19uAsEw3jogw=,tag:isuZ7lUyHfCQoU+WlHLtHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.1
